version: "3.8"

services:
  backend:
    image: guptalakshya/dd-backend:latest
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/dd_db
    networks:
      - mean-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: guptalakshya/dd-frontend:latest
    ports:
      - "4200:80"
    networks:
      - mean-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mean-net:
    external: true
